// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicIntInput,
  DefaultIntInputProps,
} from "./plasmic/swissarmy_4_dev/PlasmicIntInput";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface IntInputProps extends DefaultIntInputProps {
  value: BigInt;
  onChange?: (value: BigInt) => void;
}

function IntInput_(
  { value, onChange, ...props }: IntInputProps,
  ref: HTMLElementRefOf<"div">
) {
  return (
    <PlasmicIntInput
      root={{ ref }}
      {...props}
      text={{
        value: value.toString(),
        onChange: (e) => {
          let newBigintInstance: BigInt;
          try {
            newBigintInstance = BigInt(e.target.value);
          } catch (e) {
            newBigintInstance = BigInt(0);
          }
          onChange && onChange(newBigintInstance);
        },
      }}
      increment={{
        onClick: () => {
          onChange && onChange(value + BigInt(1));
        },
      }}
      decrement={{
        onClick: () => {
          onChange && onChange(value - BigInt(1));
        },
      }}
    />
  );
}

const IntInput = React.forwardRef(IntInput_);
export default IntInput;
