// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";

import { ScreenVariantProvider } from "../components/plasmic/swissarmy_4_dev/PlasmicGlobalVariant__Screen";
import { PlasmicRoot } from "../components/plasmic/swissarmy_4_dev/PlasmicRoot";
import SidebarItem from "../components/SidebarItem";
import { pages } from "../iopages";

function Root() {
  const sidebar = pages.map((p, i) => (
    <SidebarItem key={i} to={`/${p.id}`}>
      {p.displayName}
    </SidebarItem>
  ));
  return <PlasmicRoot>{sidebar}</PlasmicRoot>;
}

export default Root;
