// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3sWsabkqMN5rF9tgqCnVDh
// Component: EGFnv4IDIWK-5
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_swissarmy_4_dev.module.css"; // plasmic-import: 3sWsabkqMN5rF9tgqCnVDh/projectcss
import sty from "./PlasmicButton.module.css"; // plasmic-import: EGFnv4IDIWK-5/css

export type PlasmicButton__VariantMembers = {
  color: "primary" | "secondary" | "offwhite" | "transparent";
  loading: "loading";
};

export type PlasmicButton__VariantsArgs = {
  color?: SingleChoiceArg<"primary" | "secondary" | "offwhite" | "transparent">;
  loading?: SingleBooleanChoiceArg<"loading">;
};

type VariantPropType = keyof PlasmicButton__VariantsArgs;
export const PlasmicButton__VariantProps = new Array<VariantPropType>(
  "color",
  "loading"
);

export type PlasmicButton__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicButton__ArgsType;
export const PlasmicButton__ArgProps = new Array<ArgPropType>("children");

export type PlasmicButton__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultButtonProps {
  children?: React.ReactNode;
  color?: SingleChoiceArg<"primary" | "secondary" | "offwhite" | "transparent">;
  loading?: SingleBooleanChoiceArg<"loading">;
  className?: string;
}

function PlasmicButton__RenderFunc(props: {
  variants: PlasmicButton__VariantsArgs;
  args: PlasmicButton__ArgsType;
  overrides: PlasmicButton__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        { [sty.rootloading]: hasVariant(variants, "loading", "loading") }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox___4S6ES)}>
        <div
          className={classNames(projectcss.all, sty.freeBox__cg6Fm, {
            [sty.freeBoxcolor_offwhite__cg6FmjM9H]: hasVariant(
              variants,
              "color",
              "offwhite"
            ),
            [sty.freeBoxcolor_secondary__cg6FmbS3Y5]: hasVariant(
              variants,
              "color",
              "secondary"
            ),
            [sty.freeBoxcolor_transparent__cg6FmgogeH]: hasVariant(
              variants,
              "color",
              "transparent"
            ),
            [sty.freeBoxloading__cg6Fm2Cp88]: hasVariant(
              variants,
              "loading",
              "loading"
            )
          })}
        >
          {(hasVariant(variants, "loading", "loading") ? false : true)
            ? p.renderPlasmicSlot({
                defaultContents: "Button Label",
                value: args.children,
                className: classNames(sty.slotTargetChildren, {
                  [sty.slotTargetChildrencolor_offwhite]: hasVariant(
                    variants,
                    "color",
                    "offwhite"
                  ),
                  [sty.slotTargetChildrencolor_secondary]: hasVariant(
                    variants,
                    "color",
                    "secondary"
                  ),
                  [sty.slotTargetChildrencolor_transparent]: hasVariant(
                    variants,
                    "color",
                    "transparent"
                  ),
                  [sty.slotTargetChildrenloading]: hasVariant(
                    variants,
                    "loading",
                    "loading"
                  )
                })
              })
            : null}
          {(hasVariant(variants, "loading", "loading") ? true : false) ? (
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text,
                {
                  [sty.textloading]: hasVariant(variants, "loading", "loading")
                }
              )}
            >
              {hasVariant(variants, "loading", "loading")
                ? "Loading..."
                : "Enter some text"}
            </div>
          ) : null}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButton__VariantsArgs;
    args?: PlasmicButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicButton__ArgProps,
      internalVariantPropNames: PlasmicButton__VariantProps
    });

    return PlasmicButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButton";
  } else {
    func.displayName = `PlasmicButton.${nodeName}`;
  }
  return func;
}

export const PlasmicButton = Object.assign(
  // Top-level PlasmicButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicButton
    internalVariantProps: PlasmicButton__VariantProps,
    internalArgProps: PlasmicButton__ArgProps
  }
);

export default PlasmicButton;
/* prettier-ignore-end */
