// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3sWsabkqMN5rF9tgqCnVDh
// Component: el8LDJzpRP
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Container from "../../Container"; // plasmic-import: FlU_PKfwwn/component
import Button from "../../Button"; // plasmic-import: EGFnv4IDIWK-5/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_swissarmy_4_dev.module.css"; // plasmic-import: 3sWsabkqMN5rF9tgqCnVDh/projectcss
import sty from "./PlasmicIoPage.module.css"; // plasmic-import: el8LDJzpRP/css

export type PlasmicIoPage__VariantMembers = {};

export type PlasmicIoPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicIoPage__VariantsArgs;
export const PlasmicIoPage__VariantProps = new Array<VariantPropType>();

export type PlasmicIoPage__ArgsType = {
  inputs?: React.ReactNode;
  outputs?: React.ReactNode;
};

type ArgPropType = keyof PlasmicIoPage__ArgsType;
export const PlasmicIoPage__ArgProps = new Array<ArgPropType>(
  "inputs",
  "outputs"
);

export type PlasmicIoPage__OverridesType = {
  root?: p.Flex<typeof Container>;
  execute?: p.Flex<typeof Button>;
};

export interface DefaultIoPageProps {
  inputs?: React.ReactNode;
  outputs?: React.ReactNode;
  className?: string;
}

function PlasmicIoPage__RenderFunc(props: {
  variants: PlasmicIoPage__VariantsArgs;
  args: PlasmicIoPage__ArgsType;
  overrides: PlasmicIoPage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <Container
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    >
      <div className={classNames(projectcss.all, sty.freeBox__brXvj)}>
        <div className={classNames(projectcss.all, sty.freeBox__saGK)}>
          {p.renderPlasmicSlot({
            defaultContents: null,
            value: args.inputs
          })}
        </div>

        <Button
          data-plasmic-name={"execute"}
          data-plasmic-override={overrides.execute}
          className={classNames("__wab_instance", sty.execute)}
        >
          {"Execute"}
        </Button>
      </div>

      <div className={classNames(projectcss.all, sty.freeBox__en4Cv)}>
        <div className={classNames(projectcss.all, sty.freeBox__hhoZt)}>
          {p.renderPlasmicSlot({
            defaultContents: null,
            value: args.outputs
          })}
        </div>
      </div>
    </Container>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "execute"],
  execute: ["execute"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof Container;
  execute: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicIoPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicIoPage__VariantsArgs;
    args?: PlasmicIoPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicIoPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicIoPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicIoPage__ArgProps,
      internalVariantPropNames: PlasmicIoPage__VariantProps
    });

    return PlasmicIoPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicIoPage";
  } else {
    func.displayName = `PlasmicIoPage.${nodeName}`;
  }
  return func;
}

export const PlasmicIoPage = Object.assign(
  // Top-level PlasmicIoPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    execute: makeNodeComponent("execute"),

    // Metadata about props expected for PlasmicIoPage
    internalVariantProps: PlasmicIoPage__VariantProps,
    internalArgProps: PlasmicIoPage__ArgProps
  }
);

export default PlasmicIoPage;
/* prettier-ignore-end */
